


DROP TABLE IF EXISTS COMMENTS;
  
CREATE TABLE COMMENTS (
  COMMENT_ID INT AUTO_INCREMENT  PRIMARY KEY,
  TEXT VARCHAR(4000) NOT NULL,
  PARENT_COMMENT_ID INT,
  USER VARCHAR(250) NOT NULL,
  CREATED_DATE DATE  NOT NULL
);



